### ISSUE TITLE
Save queue state after a job is done. *Improvement*

### ISSUE THREAD

**Issue by MichaelSasser** [bswebdk/FFQueue#1]
FFQueue is a nice piece at first. Thumps up!

So, to the problem. If you use FFQueue with a network based type of storage system, like a NAS, for destination or source, it is possible, that the network is unstable for a moment and doesn't recover as fine as you probably hope. This causes a problem for ffmpeg, and leads to an crash. FFQueue doesn't  recognize it and crashs also. While FFQueue doesn't save the state of the queue after every job, all prepared jobs are lost. This would also help if FFQueue stops working properly.

Michael

**Comment by bswebdk** [comment]
Thank you for the suggestion, in the next release I will make sure that jobs are saved on-the-fly :)

**Comment by MichaelSasser** [comment]
Hi, thank you, that would help a lot.

**Comment by bswebdk** [comment]
No problem. Btw., you can save the items using CTRL+S on the fly :)
