### ISSUE TITLE
[Bug] Choosing to clone job on "Tool: Convert video to GIF" crashes FFQueue

### ISSUE THREAD

**Issue by Izheil** [bswebdk/FFQueue#11]
Operative System: Windows 10
Application version 1.7.57.275

When adding a job to create a gif from the tools menu everything works right, but after creating the gif creating job, if you right click it and choose "Clone job..." FFQueue crashes. All other options (Edit job, edit preset, etc...) work right.

This doesn't happen when you clone a job of a regular video conversion, where it doesn't crash.

**Comment by bswebdk** [comment]
Sorry for the late response and thanks for your report, the bug is confirmed, located and fixed. I will try to push a bug fix later this week!

**Comment by Izheil** [comment]
Thanks! Ill check back next week then.

**Comment by bswebdk** [comment]
Fixed in V1.7.58
