### ISSUE TITLE
[Feature request] Change output file extension to match preset output format on preset change

### ISSUE THREAD

**Issue by Izheil** [bswebdk/FFQueue#13]
This isn't really something critical, but when converting a video from any format (let's say h264 with .mp4 file extension) to a totally different one (let's say to vp9 with .webm file extension), even if you had specified the output format on the preset you are using, the output file extension won't change (at least this is the case if you change the preset after adding the input file). 

I understand that codecs aren't always tied to one specific file extension (specially on mkv and webm files), but would there be any way to specify which file extension to use for the output file on the preset settings if not using the output format setting?

That way when you want to export to a .webm file from an input of .mp4 for example, you won't have to change the extension of the output every time, or something similar when you are just extracting the audio of a video file to an mp3.

**Comment by bswebdk** [comment]
Sorry for the late reply, I will look into a solution for this at some point in time.

**Comment by j7j2** [comment]
Just adding a thumbs up on this request :+1:
