### ISSUE TITLE
FFQueue qt5 version for Linux KDE?

### ISSUE THREAD

**Issue by candrapersada** [bswebdk/FFQueue#14]
why is there no qt5 version of FFQueue for Linux KDE and QT?

**Comment by bswebdk** [comment]
In order to be cross platform, FFQueue uses [wxWidgets](http://www.wxwidgets.org/) as toolkit. It is possible to [configure wxWidgets to use Qt](https://docs.wxwidgets.org/3.1.3/plat_qt_install.html) instead of GTK, and by doing so FFQueue can use the Qt toolkit.

**Comment by candrapersada** [comment]
I asked for a qt5 version of FFQueue ready to use without configuring wxWidgets to use Qt, [in the download menu.](http://ffqueue.bruchhaus.dk/Download.aspx)

**Comment by bswebdk** [comment]
The Linux download from my website is rarely used as it has limited support for anything else than the current Debian/Ubuntu-version, most Linux users will build FFQueue from source. There is no pre-build version based on Qt available from my site.
