### ISSUE TITLE
[Feature request] Support Raw input

### ISSUE THREAD

**Issue by chrisxvin** [bswebdk/FFQueue#16]
I'm trying to encode a series of pictures to mp4, and input is a text file, like this:
```
file 'interp/00000001.png' # 
file 'interp/00000002.png' # 
file 'interp/00000003.png' # 
file 'interp/00000004.png' # 
file 'interp/00000005.png' # 
file 'interp/00000006.png' # 
file 'interp/00000007.png' # 
file 'interp/00000008.png' # 
file 'interp/00000009.png' # 
file 'interp/00000010.png' # 
```

For ffmpeg CLI, it should be like this:
```
-f concat -i frames.txt
```

Can you support this plz?

**Comment by chrisxvin** [comment]
Well... I found "Make video from images" under Tools menu, but I still suggest add raw input mode to "Edit job" dialog. That will be more flexibility. And I can use a job as template, just change input files.

**Comment by chrisxvin** [comment]
Tried "Make video from images", it will stuck when there are a lot of images(>20000) in a folder.
But select just a list file as input is much much faster.

**Comment by bswebdk** [comment]
"Make video from images" creates a text file with all the images found and passes the name of that text file to FFmpeg. If a huge amount of files are found, the creation of the text file may take a while and it may seem that FFQueue hangs during this process. I will try to make a visual feedback for the process at some point.

**Comment by chrisxvin** [comment]
Actually, my list file is generated by another program, so may be add an option to select the file directly?
If this function can be made to a job, that will be great😉
