### ISSUE TITLE
[Feature Request] - Add FDK-AAC to the available codec list

### ISSUE THREAD

**Issue by j7j2** [bswebdk/FFQueue#17]
Making some encoding for low bitrate (Africa / Haiti...) and the embedded ffmpeg codec doesn't allow proper use of he-aac and I don't know if there is a workaround I can use to specify manually the use of this codec. using the "custom command line argument" filed only seems to add sting of characters at the end of the command which doesn't work.

Example of an encoding I use:
ffmpeg ... _ ... -c:a libfdk_aac -profile:a aac_he -ac 1 -b:a 27k ... _ ... out.m4a

The build of non-free ffmpeg I'm using can be downloaded here
https://github.com/AnimMouse/ffmpeg-stable-autobuild

**Comment by bswebdk** [comment]
Closed; The codec is already in the list.
