### ISSUE TITLE
[Feature Request] - Add Unsharp Mask settings to internal scale filter pane

### ISSUE THREAD

**Issue by j7j2** [bswebdk/FFQueue#18]
I get confused often about how to get proper results when using the Unsharp mask parameters supported buy the built in FFMpeg Lanzcos scale filter. When I want to use it in ffqueue, I use custom video filter and my string look like this:

![unsharp-string](https://user-images.githubusercontent.com/47395884/214903349-851fe249-b36c-48f5-947c-46088cdd8138.PNG)

and as you can see I did my best to figure out how it turned out with various settings...

I'm used to the proper Radius, Strength and Threshold parameters in VirtualDub

![vdub-unsharp](https://user-images.githubusercontent.com/47395884/214902332-3600ce37-5023-4a38-8299-da29d9cbd2e8.png)

And since there is no live preview, it's often fastidious to get an idea of what the filter will look... a small third party loop tool " ffmpeg, unsharp to ffplay"  of a single frame to see real time effects would be an awesome project.

**Comment by bswebdk** [comment]
In FFQueue you have a visual implementation of the "unsharp" filter named "Sharpen" - I know, it is a bit misleading.. If you place a "Sharpen" filter right after the "Scale" filter, you should be able to achieve the same as your custom filter.
