### ISSUE TITLE
[Feature Request] - Add settings to video encoding settings (x264)

### ISSUE THREAD

**Issue by j7j2** [bswebdk/FFQueue#19]
and those other codecs to who these settings apply to?

Cabac On/Off - "-coder 1" / "-coder 0"
Level / Profile Ex: "-profile:v main -level:v 3.0"

Actually those settings I just specify them in the custom command line argument but having those in the GUI would be nice.

Are there other settings that we could add that are not implemented that I'm forgetting about?

**Comment by bswebdk** [comment]
CABAC is enabled by default, there is rarely any need to disable it. There will be better support for specific codec features at some point in the future.
