### ISSUE TITLE
subtitles in Windows/ANSI

### ISSUE THREAD

**Issue by alex6dj** [bswebdk/FFQueue#2]
In windows I'm having problems adding subtitles to the video when it contains Spanish characters like "ñ¿?", Etc.
You can add the option to select "charenc" of a listing in the subtitles. This allows you to convert them correctly using CP1252 with this option.

Thanks for the excellent work...

**Comment by bswebdk** [comment]
Have you tried to save the subtitle file with UTF-8 encoding before burning them in? I can without issues burn in subtitles with Danish, Swedish and German special characters.

**Comment by alex6dj** [comment]
OK, in UTF-8 all ok but the conversion I do daily to about 200 videos with subtitles (all in ANSI). So it would take quite a lot of manual work and the idea is to use batch conversion.
The idea would be to allow this data to be selected and placed in the conversion command, but at least it can be manually added to the filters.

It should look like this
Subtitles=sub.srt:charenc=CP1252

**Comment by bswebdk** [comment]
I am aware of the syntax for the subtitle filter and the character encoding may be implemented at some point. In the meantime I would suggest that you batch convert the encoding of the subtitles. Google will help you with this :)

**Comment by alex6dj** [comment]
OK thanks for the answer
