### ISSUE TITLE
[Feature Request] - Audio delay adjustment

### ISSUE THREAD

**Issue by j7j2** [bswebdk/FFQueue#24]
When making repacks, combining a french audio track from a dvd and all audio tracks from a blu ray, I often have to adjust audio sync. Actually, I'm using vlc to calculate how much delay i need to adjust the track and then the mkvtoolnix gui to adjust individual audio track delay and then have the thing copied back into a mp4 container by ffqueue. mkvtoolnix gui also allows me to add languages flags on those tracks for them to appear in the vlc audio track selection menu. Having a way to select the index of the multiple audio tracks being imported into a job and a panel where we can specify the details, language, delay for those tracks that have been numbered before would again save a few steps. i guess that the panel could simply list automatically imported audio tracks...

**Comment by bswebdk** [comment]
Audio Delay: You can already synchronize streams with FFQueue, in the Job Editor you can click the "[MORE]" button and enter a millisecond value for synchronization of streams. If the streams you want to sync are in the same file, you can add the same file multiple time and pick video from one and audio from another and thereby sync the streams.

Language tags: In the next version, it will be possible to declare stream indicies for metadata and this makes it possible to set audio stream language for multiple streams.

**Comment by bswebdk** [comment]
Setting language is possible in V1.7.62, read docs about metadata for further info.
