### ISSUE TITLE
Filter List not behaving? Is it me???

### ISSUE THREAD

**Issue by j7j2** [bswebdk/FFQueue#31]
Windows 7 x64
I am using this version of ffmpeg: https://github.com/AnimMouse/ffmpeg-autobuild/releases/tag/m-2023-12-05-14-07

and the latest version of ffqueue (1.7.64)

and despite a filter list that should output a 704*480 frame, the output file is ... as large as the input... (1920x1080)

I have 3 filters:
Crop: 60 top, 60 bottom;
Scale: 680x408 with lanczos resize;
Pad to size = 704*480

Am i missing something??

I have noticed that if I only put the first filter alone, the output is properly 1920*960

And I also noticed than with all 3 filters in the chain, for some reasons... Windows Explorer and VirtualDub read the file as 1920x1080 tho MediaInfo say it's a 704*480 ( shoud i drop my faith in MediaInfo ? )

It seems that the complex filter chain gets corrupted when multiple filter gets used. [0:0] to [F1], [F1] to[F3], [F3] to ????? so ffmpeg encodes 0:0 to the specified codec settings??

Here's the generated "show commands" by ffqueue...
-hide_banner -i "SourceVideo-1080p-x264.mkv" -map 0:0 -map 0:1 -filter_complex "[0:0]crop=iw:ih-120:0:60[F1];[F1]scale=680:408:flags=lanczos[F3];[F3]pad=704:480:(ow-iw)/2:(oh-ih)/2:#000000" -c:v libx264 -crf 12 -preset:v ultrafast -bf 3 -refs 9 -pix_fmt yuv420p -c:a copy -movflags faststart -aspect 16:9 -f mp4 -y "TargetVideo-480p-x264.mp4"

ALSO *** *** Since we now have at the bottom a seperate tab for messages and job#1... is it possible that when we start a job, the tab focus get switched to the active job, I mean, otherwise, it seems that nothing is happening ( no progress bar is being shown unless we manually switch tab"...

Not sure why we now have separate tabs at the bottom still... is it to see the process of remotely encoded files on other computer in my house?? I mean, I would love to get a system on which I could install FFqueue on all my devices (platform wide) and from a click, send the encoding jobs thru local network to other cpu around the house... but I do value stability over new features :-)

**Comment by j7j2** [comment]
Just to relate, i'm ... Tommy Boucher interchangeably (aka j7j2) in your ChangeLog  LoL :-)

**Comment by bswebdk** [comment]
Hi Tommy,

I will look into the filter thingy as soon as time allows it.

The split tabs / consoles was made in order to allow multiple jobs to run simultaneously, which is handy for systems with large CPU core count. If two or more encoding jobs would dump their output to the same tab, the contents of that tab would be a garbled, useless mess. So, one console for FFQueue messages and one console for each possible encoding job (selected in settings).

EDIT: Oh, if a user would look through the results of an encoding job and the tabs suddently changed that would be quite annoying, right? At least, that is why they do not change ATM.. :)

**Comment by bswebdk** [comment]
So, I have tested your problem with a 1080p source file using the command: -i "Source.tts" -map 0:0 -map 0:1 -filter_complex "[0:0]crop=iw:ih-120:0:60[F1];[F1]scale=680:408:flags=lanczos[F3];[F3]pad=704:480:(ow-iw)/2:(oh-ih)/2:#000000" -c:v libx264 -crf 12 -preset:v ultrafast -bf 3 -refs 9 -pix_fmt yuv420p -c:a copy -movflags faststart -aspect 16:9 -f mp4 -y "Destination - Test filters.mp4"

The output according to FFprobe, MediaInfo and VLC Media Player is exactely as it should be. You should probably drop your faith in Windows Explorer and VirtualDub (or select the right file?).

Btw., I redacted some info from your OP which could have become less fortunate for you to post along with your name..........

**Comment by bswebdk** [comment]
I am reopening this issue, since it is related to a change in FFmpeg >= V6.0, which affects multiple users and has also been reported to [FFmpeg's bug tracker](https://trac.ffmpeg.org/ticket/10801). I will try to fix this issue as soon as possible.

This bug does not affect the snap version.

**Comment by bswebdk** [comment]
I am closing this again since the issue should be fixed in V1.7.65.
